simulation:
  rounds: 20
model:
  layers: [2, 2, 1]
scheduler:
  idle_threshold: 0.3
  devices:
    device_A: { idle_fraction: 0.5 }
    device_B: { idle_fraction: 0.2 }
    device_C: { idle_fraction: 0.8 }
    device_D: { idle_fraction: 0.6 }
    device_E: { idle_fraction: 0.4 }
    device_F: { idle_fraction: 0.7 }
    device_G: { idle_fraction: 0.1 }
    device_H: { idle_fraction: 0.9 }
    device_I: { idle_fraction: 0.3 }
    device_J: { idle_fraction: 0.55 }
fog:
  region: us-central
cloud:
  endpoint: https://cloud.example.com
